name: diagnosticable
description: Clutterless logger capable of displaying times, positions in file.
version: 0.0.6
homepage: https://github.com/adriank/diagnosticable

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
